from sqlalchemy import Integer,String, DateTime, Table, Column
from config.db import meta

empleador = Table("empleadores",meta, 
    Column("id", String, primary_key=True),
    Column("nombre_empresa", String(50)),
    Column("nombre_jefe", String(50)),
    Column("correo", String(50)),
    Column("puesto", String(25)),
    Column("telefono", String(50)),
    Column("licenciatura_posgrado", Integer),
    Column("puesto_egresado", String(255)),
    Column("antiguedad", Integer),
    Column("uno", Integer),
    Column("dosa", Integer),
    Column("dosb", String(50)),
    Column("tresa", Integer),
    Column("tresb", String(50)),
    Column("cuatroa", Integer),
    Column("cuatrob", Integer),
    Column("cuatroc", Integer),
    Column("cuatrod", Integer),
    Column("cuatroe", Integer),
    Column("cuatrof", String(50)),
    Column("cinco", String(50)),
    Column("seisa", Integer),
    Column("seisb", String(50)),
    Column("sietea", Integer),
    Column("sieteb", Integer),
    Column("sietec", Integer),
    Column("sieted", Integer),
    Column("sietee", Integer),
    Column("sietef", String(50)),
    Column("ocho", String(50)),
    Column("nuevea", Integer),
    Column("nueveb", Integer),
    Column("nuevec", Integer),
    Column("nueved", Integer),
    Column("nuevee", Integer),
    Column("nuevef", Integer),
    Column("nueveg", String(50)),
    Column("dieza", Integer),
    Column("diezb", Integer),
    Column("diezc", Integer),
    Column("diezd", Integer),
    Column("dieze", Integer),
    Column("diezf", Integer),
    Column("oncea", Integer),
    Column("onceb", String(50)),
    Column("doce", String(50)),)